### ISSUE TITLE
加载到最后就卡死了。

### ISSUE THREAD

**Issue by elysiawen** [AkashiCoin/nonebot_plugin_mockingbird#1]
![QQ截图20220522012327](https://user-images.githubusercontent.com/46924591/169662649-b587d40a-57bf-4e86-9e80-d5dd23c0b6f2.png)
加载到这里就不动了卡死了。

**Comment by AkashiCoin** [comment]
请使用最新版的插件

**Comment by elysiawen** [comment]
试了试，似乎还是这样，依旧是加载到这里卡死。
