### ISSUE TITLE
求助

### ISSUE THREAD

**Issue by Passerby-D** [AkashiCoin/nonebot_plugin_mockingbird#14]
这个问题可能会很铸币，但我确实不知道怎么解决，麻烦大佬看看
就是连我插件都装不上去，不管是nb_cli装还是pip装都报错
ERROR: Ignored the following versions that require a different python version: 0.1.1 Requires-Python >=3.8,<3.10; 0.1.2 Requires-Python >=3.8,<3.10; 0.1.3 Requires-Python >=3.8,<3.10; 0.2.0 Requires-Python >=3.8,<3.10; 0.2.1 Requires-Python >=3.8,<3.10
ERROR: Could not find a version that satisfies the requirement torchvision<0.12.0,>=0.11.2 (from nonebot-plugin-mockingbird) (from versions: 0.1.6, 0.1.7, 0.1.8, 0.1.9, 0.2.0, 0.2.1, 0.2.2, 0.2.2.post2, 0.2.2.post3, 0.12.0, 0.13.0, 0.13.1)
ERROR: No matching distribution found for torchvision<0.12.0,>=0.11.2

这个意思是让我换个python版本吗，我试了很久不知道怎么操作

**Comment by AkashiCoin** [comment]
需要py3.8或者3.9
