### ISSUE TITLE
已经安装相关包但提示"No module named 'mockingbirdforuse'"

### ISSUE THREAD

**Issue by chordfish-k** [AkashiCoin/nonebot_plugin_mockingbird#15]
![@~(OR%)OGTQ_ 4R5N`SO`}O](https://user-images.githubusercontent.com/17528205/187447237-98f93216-e45d-4bc0-ac0c-b34d17689931.png)
![)UHVYRBR%~%N@(OKRKMFLPD](https://user-images.githubusercontent.com/17528205/187447915-9b2a8f80-22c6-4a78-8286-f6376005a4ad.png)

**Comment by AkashiCoin** [comment]
请检查相关包是否安装到了相关环境

**Comment by chordfish-k** [comment]
> 

没有
