### ISSUE TITLE
启动bot加载 时服务器会卡死

### ISSUE THREAD

**Issue by sinonchen** [AkashiCoin/nonebot_plugin_mockingbird#16]
在正常使nonebot_plugin_mockingbird用nonebot_plugin_mockingbir一段时间后，启动bot加载到插件式服务器会直接卡死
![屏幕截图 2022-09-12 013919](https://user-images.githubusercontent.com/53052742/189541415-1e924111-7d51-4b07-8228-4b736e942610.png)

**Comment by AkashiCoin** [comment]
如果配置过低不推荐使用
