### ISSUE TITLE
Exception: Please set synthesizer path first

### ISSUE THREAD

**Issue by ghost** [AkashiCoin/nonebot_plugin_mockingbird#17]
请问大佬，这个错误是为啥 ，ffmpeg已经安装
![J(FFOERM~FRWU Y``}3~WLV](https://user-images.githubusercontent.com/54128025/189902542-11dbc4c0-cd28-4d1b-a36b-8217a7e07fa6.png)
Ubuntu Server 22.04 64位，python-3.9.13，nonebot以及cqhttp均为最新版
求解答，不胜感激

**Comment by AkashiCoin** [comment]
大概是模型下载失败，可以选择自行去[https://pan.yropo.top/source/mockingbird/](https://pan.yropo.top/source/mockingbird/)下载模型，并将其导入

**Comment by ghost** [comment]
多谢！重新下载后解决问题！！！
