### ISSUE TITLE
nonebot.adapters.onebot.v11.exception.ActionFailed: <ActionFailed data=None, echo='17', msg='SEND_MSG_API_ERROR', retcode=100, status='failed', wording='请参考 go-cqhttp 端输出'>

### ISSUE THREAD

**Issue by xiaoyang212** [AkashiCoin/nonebot_plugin_mockingbird#18]
nonebot.adapters.onebot.v11.exception.ActionFailed: <ActionFailed data=None, echo='17', msg='SEND_MSG_API_ERROR', retcode=100, status='failed', wording='请参考 go-cqhttp 端输出'> 请问这该如何解决

**Comment by AkashiCoin** [comment]
请参考 go-cqhttp 端输出
