### ISSUE TITLE
可以成功加载，但是无法使用

### ISSUE THREAD

**Issue by EE0CFF** [AkashiCoin/nonebot_plugin_mockingbird#2]
traceback如下
![image](https://user-images.githubusercontent.com/105940804/169775868-c2da3937-5391-43b0-9c57-c7cecc5a32b8.png)

应该是下载模型出错，请问应该如何重新下载模型？
重启bot后显示加载模型，但是在控制台看硬盘容量还是没有下载
![image](https://user-images.githubusercontent.com/105940804/169776179-e2daa617-b772-4712-b9e0-877ec4c55632.png)

**Comment by Elijah-0616** [comment]
![image](https://user-images.githubusercontent.com/60286615/169808748-851c658b-8b53-4471-8d11-e90e34bb8b21.png)

![image](https://user-images.githubusercontent.com/60286615/169809062-b6ac66d1-8fc3-4e93-a490-2f18f9be79bf.png)

我跟你有类似的问题，我的是提示模型下载失败，我根据控制台的消息手动下载后放进了文件夹，插件能够启动，但是执行的时候会报错

**Comment by AkashiCoin** [comment]
可以修改自己dns为114.114.114.114

**Comment by Elijah-0616** [comment]
> 可以修改自己dns为114.114.114.114

感谢回复，我试一下

**Comment by SEAFHMC** [comment]
> > 可以修改自己dns为114.114.114.114
> 
> 感谢回复，我试一下

朋友，你解决了吗。我也遇到了同样的问题。

**Comment by AkashiCoin** [comment]
可以参考这个issue[zhenxun-org/nonebot_plugins_zhenxun_bot/issues/43](https://github.com/zhenxun-org/nonebot_plugins_zhenxun_bot/issues/43)

**Comment by AkashiCoin** [comment]
下载地址问题已修，可以使用了
