### ISSUE TITLE
Coud not initialize NNPACK

### ISSUE THREAD

**Issue by SEAFHMC** [AkashiCoin/nonebot_plugin_mockingbird#4]
操作系统：Ubuntu 22.04
Python版本：3.10.4
问题描述：
![IMG_20220524_125627](https://user-images.githubusercontent.com/9484642/169952551-5f1b57bf-6f2a-4560-a1cd-57d9670276e5.jpg)
向bot发送指令后出现如上报错，并且Bot会发送一秒钟的空语音。

**Comment by SEAFHMC** [comment]
是我机器不行吗（

**Comment by AkashiCoin** [comment]
> 是我机器不行吗（

这样的(
