### ISSUE TITLE
Debian系统使用nb下载插件会出现缺少aiofiles moduel，解决后运行指令无效

### ISSUE THREAD

**Issue by EE0CFF** [AkashiCoin/nonebot_plugin_mockingbird#6]
![image](https://user-images.githubusercontent.com/105940804/169996157-4342ac05-59a9-4b44-915c-95a38a72d5f6.png)

自行pip install aiofiles以后可以解决
在运行之后也成功下载模型，插件也成功加载，但是实测输入指令（除显示模型指令外）没有反应，输入“说 xxx”的指令以后，输出的语音只有1秒（无论让它说什么话都是），而且没有声音（仅有一声轻微喷麦音）
![image](https://user-images.githubusercontent.com/105940804/170003015-6372e6b7-1c0a-4018-8af4-d7ad71ded827.png)
![image](https://user-images.githubusercontent.com/105940804/170003564-9d43a614-88e2-449a-b6dd-3224644c1a40.png)

**Comment by AkashiCoin** [comment]
修改精度为1000，并重新下载，模型的模板文件更新了

**Comment by EE0CFF** [comment]
> 修改精度为1000，并重新下载，模型的模板文件更新了

精度范围不是3-9吗，是修改句长还是就是精度

**Comment by AkashiCoin** [comment]
> > 修改精度为1000，并重新下载，模型的模板文件更新了
> 
> 精度范围不是3-9吗，是修改句长还是就是精度

说错了，句长，然后最好更新到最新版本

**Comment by EE0CFF** [comment]
> > > 修改精度为1000，并重新下载，模型的模板文件更新了
> > 
> > 
> > 精度范围不是3-9吗，是修改句长还是就是精度
> 
> 说错了，句长，然后最好更新到最新版本

已解决，感谢解答
